name = "SymbolicCore"
uuid = "4793ef6c-1cf0-4a9b-b756-f363b41b2280"
authors = ["sglez"]
version = "0.0.1-DEV"

[compat]
julia = "1.10, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
